'use client';
import {useEffect,useMemo,useState} from 'react'; import TraceCanvas,{Step} from '../components/TraceCanvas'; import {GitBranch,RefreshCw,Clock3,Activity,Database} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type FullStep=Step&{input:any;output:any;state_snapshot_before?:any;metrics:any};
export default function Home(){
 const [traceId,setTraceId]=useState('trc_demo_001'); const [steps,setSteps]=useState<FullStep[]>([]); const [idx,setIdx]=useState(0); const [prompt,setPrompt]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const current=steps[idx];
 const load=async()=>{setBusy(true);try{const r=await fetch(`${API}/api/v1/traces/${traceId}`);if(!r.ok)throw new Error('Trace not found');const d=await r.json();setSteps(d.steps);setIdx(0);setPrompt(d.steps?.[0]?.input?.messages?.[0]?.content||d.steps?.[0]?.input?.system_prompt||'');setMessage(`Loaded ${d.steps.length} recorded steps`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const select=(id:string)=>{const i=steps.findIndex(s=>s.step_id===id);if(i>=0){setIdx(i);setPrompt(steps[i].input?.messages?.[0]?.content||steps[i].input?.system_prompt||'')}};
 const branch=async()=>{if(!current)return;setBusy(true);try{const r=await fetch(`${API}/api/v1/replay/branch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parent_trace_id:traceId,fork_step_id:current.step_id,modified_prompt:prompt})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Branch failed');setTraceId(d.new_trace_id);setMessage(`Created ${d.new_trace_id} from ${current.step_id}`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const metrics=useMemo(()=>steps.reduce((a,s)=>({lat:a.lat+(s.metrics?.latency_ms||0),tok:a.tok+(s.metrics?.prompt_tokens||0)+(s.metrics?.completion_tokens||0)}),{lat:0,tok:0}),[steps]);
 return <main style={{minHeight:'100vh',padding:24,maxWidth:1500,margin:'auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid #1e293b',paddingBottom:18,marginBottom:18}}><div><div style={{fontSize:22,fontWeight:800,display:'flex',gap:10,alignItems:'center'}}><span style={{width:10,height:10,borderRadius:99,background:'#38bdf8'}}/>Agent Time-Travel Debugger</div><div className="muted mono" style={{fontSize:12,marginTop:5}}>{traceId}</div></div><div style={{display:'flex',gap:8}}><button onClick={load} className="panel" style={{padding:'10px 14px',cursor:'pointer'}}><RefreshCw size={15}/></button><button onClick={branch} disabled={busy||!current} style={{border:0,borderRadius:9,padding:'10px 16px',background:'#0284c7',color:'#fff',fontWeight:700,cursor:'pointer',display:'flex',gap:8,alignItems:'center'}}><GitBranch size={16}/>{busy?'Working…':'Fork & Replay Branch'}</button></div></header>
  {message&&<div className="panel" style={{padding:10,marginBottom:14,fontSize:13}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(340px,1fr)',gap:18}}>
   <section><div className="panel" style={{overflow:'hidden'}}><TraceCanvas steps={steps} selected={current?.step_id||null} onSelect={select}/></div><div className="panel" style={{padding:16,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,marginBottom:8}}><span className="muted">TIMELINE SCRUBBER</span><span className="mono" style={{color:'#38bdf8'}}>{steps.length?`Step ${idx+1} / ${steps.length}`:'No trace'}</span></div><input type="range" min={0} max={Math.max(0,steps.length-1)} value={idx} onChange={e=>select(steps[+e.target.value].step_id)} style={{width:'100%'}}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginTop:14}}>{[[Activity,'Steps',steps.length],[Clock3,'Latency',`${metrics.lat}ms`],[Database,'Tokens',metrics.tok]].map(([I,l,v]:any)=><div className="panel" style={{padding:14}} key={l}><I size={16}/><div className="muted" style={{fontSize:11,marginTop:8}}>{l}</div><div style={{fontSize:18,fontWeight:800}}>{v}</div></div>)}</div></section>
   <aside className="panel" style={{padding:18,minHeight:610}}><div style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid #1e293b',paddingBottom:12}}><div><div style={{fontWeight:800}}>Inspector</div><div className="muted mono" style={{fontSize:11}}>{current?.step_id||'—'} · {current?.step_type||'—'}</div></div><span className="mono" style={{color:'#38bdf8',fontSize:12}}>{current?.metrics?.latency_ms||0} ms</span></div><label className="muted" style={{display:'block',fontSize:11,fontWeight:700,margin:'16px 0 6px'}}>PROMPT / INPUT — EDIT TO BRANCH</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} style={{width:'100%',height:120,background:'#020617',border:'1px solid #334155',borderRadius:9,color:'#e2e8f0',padding:10,resize:'vertical'}}/><label className="muted" style={{display:'block',fontSize:11,fontWeight:700,margin:'16px 0 6px'}}>RECORDED INPUT</label><pre style={{background:'#020617',padding:12,borderRadius:9,overflow:'auto',maxHeight:180,fontSize:11}}>{JSON.stringify(current?.input||{},null,2)}</pre><label className="muted" style={{display:'block',fontSize:11,fontWeight:700,margin:'16px 0 6px'}}>RECORDED OUTPUT</label><pre style={{background:'#020617',padding:12,borderRadius:9,overflow:'auto',maxHeight:180,fontSize:11,color:'#86efac'}}>{JSON.stringify(current?.output||{},null,2)}</pre></aside>
  </div>
 </main>
}